# Generated by Django 2.0.4 on 2018-04-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confidence',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('front_item', models.TextField()),
                ('back_item', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('datee', models.CharField(max_length=255)),
                ('news', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Frequent',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('support', models.FloatField()),
                ('itemsets', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
            ],
        ),
    ]
